# Generated by Django 6.0.6 on 2026-06-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_examquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('UNIT_TEST', 'Unit Test'), ('MID_TERM', 'Mid Term'), ('FINAL_EXAM', 'Final Exam')], default='UNIT_TEST', max_length=20),
        ),
    ]
